### ISSUE TITLE
Waiting for client connection...

### ISSUE THREAD

**Issue by bereska** [rorr73/LifeSOSpy_MQTT#1]
hi Richard, thanks for this great tool to give my lifesos a second life)
I just ran into a small issue:

pi@bereskapi-ha:/opt/mosquitto $ /home/pi/.local/bin/lifesospy_mqtt -e
lifesospy_mqtt v0.10.6 - MQTT client to report state of LifeSOS security system and devices.

Waiting for client connection...

it hangs on there for ever(

i think the problem is the BF-210 ethernet adapter I got from a third country which apparently has been used before.
I cannot access it via web interface with default user and password admin:admin
it shows up on my LAN no problem and gets an ip address from my router
and i can ping it too
but when I run nmap it gives me this:

MacBook-Air-DG:~ bereska$ nmap -p- 192.168.2.247
Starting Nmap 7.70 ( https://nmap.org ) at 2018-11-25 21:50 MSK
Nmap scan report for 192.168.2.247
Host is up (0.0049s latency).
Not shown: 65533 closed ports
PORT   STATE SERVICE
80/tcp open  http
99/tcp open  metagram

so the listening port 1860 is closed

is there a way to reset this adapter? so I could access and configure it?

thanks for your help
Dmitry

**Comment by bereska** [comment]
please disregard the previous post
stupid me! I should have read the BF-210 manual to the end to see the reset option
all is set now!
the LifeSOS has successfully connected to my mosquitto in docker on rpi 3 and the control panel with all the devices (except for the remote) has appeared in Homeassistant UI
However when running 'lifesospy_mqtt' command I see the following:

pi@bereskapi-ha:/opt/mosquitto $ /home/pi/.local/bin/lifesospy_mqtt   
lifesospy_mqtt v0.10.6 - MQTT client to report state of LifeSOS security system and devices.

2018-11-26 16:11:10 INFO  (MainThread) [lifesospy.baseunit] Connected successfully
2018-11-26 16:11:10 WARNING (MainThread) [hbmqtt.client] Client not connected, waiting for it
2018-11-26 16:11:10 WARNING (MainThread) [hbmqtt.client] Client not connected, waiting for it
2018-11-26 16:11:10 INFO  (MainThread) [lifesospy.baseunit] Discovering devices and getting initial state...
2018-11-26 16:11:10 WARNING (MainThread) [hbmqtt.mqtt.protocol.handler] Received PUBACK for unknown pending message Id: '2'
2018-11-26 16:11:10 INFO  (MainThread) [transitions.core] Exited state new
2018-11-26 16:11:10 INFO  (MainThread) [transitions.core] Entered state connected
2018-11-26 16:11:10 WARNING (MainThread) [hbmqtt.mqtt.protocol.handler] Received PUBACK for unknown pending message Id: '1'
2018-11-26 16:11:11 ERROR (MainThread) [asyncio] Task was destroyed but it is pending!
task: <Task pending coro=<Translator._async_publish() done, defined at /home/pi/.local/lib/python3.5/site-packages/lifesospy_mqtt/translator.py:670> wait_for=<Future pending cb=[Task._wakeup()]>>
2018-11-26 16:11:11 ERROR (MainThread) [asyncio] Task was destroyed but it is pending!
task: <Task pending coro=<Translator._async_publish() done, defined at /home/pi/.local/lib/python3.5/site-packages/lifesospy_mqtt/translator.py:670> wait_for=<Future pending cb=[Task._wakeup()]>>
2018-11-26 16:11:11 ERROR (MainThread) [lifesospy.baseunit] Unhandled exception in on_device_added callback
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/lifesospy/baseunit.py", line 765, in _handle_response
    self._on_device_added(self, device)
  File "/home/pi/.local/lib/python3.5/site-packages/lifesospy_mqtt/translator.py", line 279, in _baseunit_device_added
    if device_config.ha_name:
AttributeError: 'NoneType' object has no attribute 'ha_name'
2018-11-26 16:11:11 ERROR (MainThread) [lifesospy.baseunit] Unhandled exception in on_device_added callback
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/lifesospy/baseunit.py", line 765, in _handle_response
    self._on_device_added(self, device)
  File "/home/pi/.local/lib/python3.5/site-packages/lifesospy_mqtt/translator.py", line 279, in _baseunit_device_added
    if device_config.ha_name:
AttributeError: 'NoneType' object has no attribute 'ha_name'
2018-11-26 16:11:15 INFO  (MainThread) [lifesospy.baseunit] Device discovery completed and got initial state

Is this an issue?

Also when disarming the panel in UI I have to tap the DISARM button twice for the UI to display the disarmed mode even though it actually disarms the system after the first tap
I s there anything I can do to fix this?

thank you
Dmitry

**Comment by bereska** [comment]
also I fail to run your program on reboot
I tried creating a systemd service:

# /etc/systemd/system/lifesosd.service

[Unit]
Description=lifesos_mqtt for homeassistant
Requires=docker.service docker-compose-opt.service
After=docker.service docker-compose-opt.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=/home/pi/.local/bin
ExecStart=/home/pi/.local/bin/lifesospy_mqtt -d
TimeoutStartSec=0
user=pi

[Install]
WantedBy=multi-user.target

but it fails to start:

pi@bereskapi-ha:~ $ systemctl status lifesosd.service
● lifesosd.service - lifesos_mqtt for homeassistant
   Loaded: loaded (/etc/systemd/system/lifesosd.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2018-11-28 11:12:22 MSK; 16s ago
  Process: 24182 ExecStart=/home/pi/.local/bin/lifesospy_mqtt -d (code=exited, status=1/FAILURE)
 Main PID: 24182 (code=exited, status=1/FAILURE)
      CPU: 156ms

ноя 28 11:12:22 bereskapi-ha systemd[1]: Starting lifesos_mqtt for homeassistant...
ноя 28 11:12:22 bereskapi-ha lifesospy_mqtt[24182]: Traceback (most recent call last):
ноя 28 11:12:22 bereskapi-ha lifesospy_mqtt[24182]:   File "/home/pi/.local/bin/lifesospy_mqtt", line 7, in <module>
ноя 28 11:12:22 bereskapi-ha lifesospy_mqtt[24182]:     from lifesospy_mqtt.__main__ import main
ноя 28 11:12:22 bereskapi-ha lifesospy_mqtt[24182]: ImportError: No module named 'lifesospy_mqtt'
ноя 28 11:12:22 bereskapi-ha systemd[1]: lifesosd.service: Main process exited, code=exited, status=1/FAILURE
ноя 28 11:12:22 bereskapi-ha systemd[1]: Failed to start lifesos_mqtt for homeassistant.
ноя 28 11:12:22 bereskapi-ha systemd[1]: lifesosd.service: Unit entered failed state.
ноя 28 11:12:22 bereskapi-ha systemd[1]: lifesosd.service: Failed with result 'exit-code'.
Warning: lifesosd.service changed on disk. Run 'systemctl daemon-reload' to reload units.

if i just leave lifesospy_mqtt -d running, it does not stay persistent either after rebooting or restarting home assistant 

any help is much appreciated
thank you

**Comment by rorr73** [comment]
Hi! Sorry for not responding sooner, I'm new to Github and assumed it would email me when issues were posted.

Regarding the issues:

**1. Daemon service script**

Here's a copy of what I'm using and works for me:

```
[Unit]
Description=LifeSOSpy MQTT
After=network.target

[Service]
Type=simple
User=%i
ExecStart=/usr/local/bin/lifesospy_mqtt -l -p -d

[Install]
WantedBy=multi-user.target
```

I think the key difference here is using 'type=simple' instead of 'type=oneshot', as the '-d' daemon switch will fork the daemon process into the background and exit immediately.

**2. Log errors**

The first few errors can be ignored, they're from MQTT in relation to acknowledgements after shutting down the previous instance of LifeSOSpy.

The ones related to 'on_device_added' indicate one of your devices isn't listed in the config.yaml (possibly the remote which you mentioned was missing). I will need to add a fix to handle this gracefully instead of erroring (possibly a warning that says device not found in config). The easiest way to resolve this from your end would be finding which device is missing, by running ```lifesospy_mqtt -e``` to list the devices and compare it to those in config.yaml.

**3. Disarm update**

This is an odd one! 

For starters, try using an MQTT client to subscribe to the topics (refer Step 6 of the [Quickstart](https://lifesospy-mqtt.readthedocs.io/en/latest/quickstart.html)) and checking if ```home/alarm/ha_state``` topic publishes ```disarmed``` immediately; If so, it narrows down the issue to a HA configuration issue rather than MQTT or LifeSOSpy. If not, I'd probably need more details to determine the cause (ie. a copy of the log+config files).

**Comment by bereska** [comment]
Hi Richard,

no problem
thanks for responding

I have replaced Type=oneshot with Type=simple:

pi@bereskapi-ha:~ $ sudo systemctl start lifesosd.service
pi@bereskapi-ha:~ $ systemctl status lifesosd.service
● lifesosd.service - lifesos_mqtt for homeassistant
   Loaded: loaded (/etc/systemd/system/lifesosd.service; disabled;
vendor preset: enabled)
   Active: active (exited) (Result: exit-code) since Sun 2019-01-06
07:53:24 MSK; 27min ago
  Process: 26020 ExecStart=/usr/bin/python3
/home/pi/.local/bin/lifesospy_mqtt -l -p -d (code=exited, status=78)
 Main PID: 26020 (code=exited, status=78)
      CPU: 1.663s

янв 06 07:53:24 bereskapi-ha systemd[1]: Started lifesos_mqtt for
homeassistant.
янв 06 07:53:26 bereskapi-ha python3[26020]: lifesospy_mqtt v0.10.6 -
MQTT client to report state of LifeSOS security system and dev
янв 06 07:53:26 bereskapi-ha python3[26020]: A default configuration
file has been created:
янв 06 07:53:26 bereskapi-ha python3[26020]:
/root/.lifesospy_mqtt/config.yaml
янв 06 07:53:26 bereskapi-ha python3[26020]: Please edit any settings as
needed then restart.
янв 06 07:53:26 bereskapi-ha systemd[1]: lifesosd.service: Main process
exited, code=exited, status=78/n/a

here is the lifesosd.service file:

# /etc/systemd/system/lifesosd.service

[Unit]
Description=lifesos_mqtt for homeassistant
Requires=docker.service docker-compose-opt.service
After=network.target

[Service]
Type=simple
RemainAfterExit=yes
#WorkingDirectory=/home/pi/.local/bin
#Environment=PYTHONPATH=/home/pi/.local/lib/python3.5/site-packages
ExecStart=/usr/bin/python3 /home/pi/.local/bin/lifesospy_mqtt -l -p -d
TimeoutStartSec=0
user=pi

[Install]
WantedBy=multi-user.target

I also tried coping:
sudo cp /home/pi/.lifesospy_mqtt/config.yaml
/root/.lifesospy_mqtt/config.yaml
but the result is the same as above

I have also noticed that the daemon successfully starts ONLY after this
command:
pi@bereskapi-ha:~ $ /home/pi/.local/bin/lifesospy_mqtt -d
pi@bereskapi-ha:~ $ ps aux | grep lifesospy_mqtt
pi       15094  4.7  1.9  28420 18424 ?        S    08:45   0:02
/usr/bin/python3 /home/pi/.local/bin/lifesospy_mqtt -d
pi       15514  0.0  0.0   5996   536 pts/0    S+   08:46   0:00 grep
--color=auto lifesospy_mqtt

if i run it with -l -p, the daemon does not start:
pi@bereskapi-ha:~ $ /home/pi/.local/bin/lifesospy_mqtt -l -p -d
lifesospy_mqtt v0.10.6 - MQTT client to report state of LifeSOS security
system and devices.

Starting daemon.
pi@bereskapi-ha:~ $ ps aux | grep lifesospy_mqtt
pi       15091  0.0  0.0   5996   544 pts/0    S+   08:45   0:00 grep
--color=auto lifesospy_mqtt

any help is much appreciated
Dmitry

**Comment by rorr73** [comment]
Looks like a couple of things are going on here:

In your .service file, change ```user=pi``` to ```User=pi``` (note the capital 'U'). I tried it on my machine, and lower case 'user' isn't recognised (running ```systemctl status``` indicates 'user' is unknown), which is probably why the log indicates it was running under root instead of pi. Since it didn't find the config file in the root user's path, it created a default config file and exited.

The '-l' (create log file) and '-p' (create pid file) both need to create a file in the same ```.lifesospy_mqtt``` folder that contains the config file, so if it fails it means it probably didn't have write access to the folder. This may be related to the above issue where it was running under the root user instead of pi user, so it may resolve itself when you make that change. If not, you may need to adjust the permissions on the folder.

I hope this helps.

**Comment by bereska** [comment]
thank you for your reply
i have tried this but no dice

pi@bereskapi-ha:~ $ sudo systemctl start lifesosd.service
pi@bereskapi-ha:~ $ ps aux | grep lifesospy_mqtt
pi        5320  0.0  0.0   5996   548 pts/0    S+   20:40   0:00 grep --color=auto lifesospy_mqtt
pi@bereskapi-ha:~ $ systemctl status lifesosd.service
● lifesosd.service - lifesos_mqtt for homeassistant
   Loaded: loaded (/etc/systemd/system/lifesosd.service; disabled; vendor preset: enabled)
   Active: active (exited) (Result: exit-code) since Sun 2019-01-06 07:53:24 MSK; 5 days ago
 Main PID: 26020 (code=exited, status=78)
      CPU: 0
   CGroup: /system.slice/lifesosd.service

янв 06 07:53:24 bereskapi-ha systemd[1]: Started lifesos_mqtt for homeassistant.
янв 06 07:53:26 bereskapi-ha python3[26020]: lifesospy_mqtt v0.10.6 - MQTT client to report state of LifeSOS security system and dev
янв 06 07:53:26 bereskapi-ha python3[26020]: A default configuration file has been created:
янв 06 07:53:26 bereskapi-ha python3[26020]: /root/.lifesospy_mqtt/config.yaml
янв 06 07:53:26 bereskapi-ha python3[26020]: Please edit any settings as needed then restart.
янв 06 07:53:26 bereskapi-ha systemd[1]: lifesosd.service: Main process exited, code=exited, status=78/n/a

if i run '/home/pi/.local/bin/lifesospy_mqtt -l -p -d
log and pid files are created in /home/pi/.lifesospy_mqtt but however it fails to start to daemon:
pi@bereskapi-ha:~ $ ls -lash .lifesospy_mqtt
итого 1,1M
4,0K drwxr-xr-x  2 pi pi 4,0K янв  6 08:19 .
4,0K drwxr-xr-x 11 pi pi 4,0K янв  5 17:13 ..
4,0K -rw-r--r--  1 pi pi 3,8K ноя 26 11:53 config.yaml
1,1M -rw-rw-rw-  1 pi pi 1,1M ноя 27 19:51 log
4,0K -rw-r--r--  1 pi pi 2,5K ноя 26 18:32 log.2018-11-26
4,0K -rw-r--r--  1 pi pi    5 ноя 27 19:51 pid
pi@bereskapi-ha:~ $ ps aux | grep lifesospy_mqtt
pi        8014  0.0  0.0   5996   548 pts/0    S+   17:17   0:00 grep --color=auto lifesospy_mqtt

I can start the daemon only running this:
pi@bereskapi-ha:~ $ /home/pi/.local/bin/lifesospy_mqtt -d
lifesospy_mqtt v0.10.6 - MQTT client to report state of LifeSOS security system and devices.

Starting daemon.
pi@bereskapi-ha:~ $ ps aux | grep lifesospy_mqtt
pi       17925 26.8  1.9  28436 18352 ?        S    21:21   0:01 /usr/bin/python3 /home/pi/.local/bin/lifesospy_mqtt -d
pi       17980  0.0  0.0   5996   580 pts/0    S+   21:21   0:00 grep --color=auto lifesospy_mqtt

all permission seem to be correct too:
4,0K drwxr-xr-x  2 pi   pi   4,0K янв  6 08:19 .lifesospy_mqtt

I am lost ...
the only other thing I can think of if that when I installed lifesospy_mqtt I ran it without sudo:
'pip3 install lifesospy_mqtt'

**Comment by bereska** [comment]
DISARM UPDATE
when I arm lifeSOS I see these logs in home assistant:

2019-01-12 01:47:58 DEBUG (MainThread) [homeassistant.components.mqtt] Transmitting message on home/alarm/operation_mode/set: Away,
2019-01-12 01:47:59 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on home/alarm/ha_state: b'armed_away'

it always works great and the icon changes to ARMED in my GUI

but when I disarm it at FIRST click I see this:

2019-01-12 01:54:42 DEBUG (MainThread) [homeassistant.components.mqtt] Transmitting message on home/alarm/operation_mode/set: Disarm,
2019-01-12 01:54:42 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on home/alarm/ha_state: b'disarmed',
2019-01-12 01:54:43 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on home/alarm/ha_state: b'armed_away'

while lifeSOS actually gets disarmed the icon does not switch to DISARMED

at SECOND click i see this:

2019-01-12 01:55:13 DEBUG (MainThread) [homeassistant.components.mqtt] Transmitting message on home/alarm/operation_mode/set: Disarm,
2019-01-12 01:55:13 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on home/alarm/ha_state: b'disarmed'

this time the icon switched to DISARMED as it should

what other logs and configs do I need to look at to resolve this?
thank you

**Comment by rorr73** [comment]
Unfortunately, I'm not sure there's much else I can think of regarding starting the daemon as a service. It appears it is still running as root in the log you posted. One possibility might be to override the working directory (default is ~/.lifesospy_mqtt) using the ``-w`` argument to somewhere else, and give it full permissions, eg:

```
sudo mkdir /usr/share/lifesospy
sudo chmod a+rwx /usr/share/lifesospy
cp ~/.lifesospy_mqtt/config.yaml /usr/share/lifesospy
lifesospy -l -w /usr/share/lifesospy
```

If that works, you could then take away permissions to /usr/share/lifesospy afterwards as needed.

Regarding the disarm issue: the HA log indicates it is receiving 'disarmed' followed almost immediately by 'armed_away' which would explain why it doesn't update. I'm wondering if you could enable additional logging on the LifeSOSpy_MQTT side and attach the log file for me? Referring at [this section](https://lifesospy-mqtt.readthedocs.io/en/latest/configuration.html#logger-settings) of the docs, the config.yaml needs to be modified to uncomment (remove the '#') from the bottom three lines so it looks like this:

```
# Settings to configure logging
# Valid severity levels are:
# critical, error, warning, info, debug
logger:

  default: info
  
  namespaces:
    lifesos: debug
    paho.mqtt.client: debug
```

**Comment by bereska** [comment]
[logLifeSOSpy2019-01-13.txt](https://github.com/rorr73/LifeSOSpy_MQTT/files/2752602/logLifeSOSpy2019-01-13.txt)
here is the log file
I killed lifesospy_mqtt and then I ran:
pi@bereskapi-ha:~ $ /home/pi/.local/bin/lifesospy_mqtt -d -l
then I just disarmed it with two clicks and finally armed it back with one click
thank you

**Comment by rorr73** [comment]
It appears from the log that your base unit uses a different event pattern to mine when switching modes. I've made a change to the LifeSOSpy library that should hopefully support it.

When you get the chance, could you please update to LifeSOSpy_MQTT version 0.11.0, and verify the issue is resolved?

**Comment by bereska** [comment]
Hi Richard,

it works like a charm now)
thank you for your time and help

i'll try to get that systemd service running and report back

do you happen to have any zigbee devices in your HA?
can i email you directly?

regards,
Dmitry

**Comment by bereska** [comment]
SYSTEMD UPDATE
I got it working with lifesospy_mqtt 0.11.0!
pi@bereskapi-ha:~ $ sudo systemctl status lifesosd.service
● lifesosd.service - lifesos_mqtt for homeassistant
   Loaded: loaded (/etc/systemd/system/lifesosd.service; disabled; vendor preset: enabled)
   Active: active (running) since Mon 2019-01-14 00:32:37 MSK; 12s ago
 Main PID: 20095 (python3)
      CPU: 2.528s
   CGroup: /system.slice/lifesosd.service
           └─20095 /usr/bin/python3 /home/pi/.local/bin/lifesospy_mqtt -d -l

янв 14 00:32:37 bereskapi-ha systemd[1]: Started lifesos_mqtt for homeassistant.

I think the new package and reboot did the job)
thank you

**Comment by rorr73** [comment]
Glad to hear it's running smoothly now!
