### ISSUE TITLE
Using serial port 

### ISSUE THREAD

**Issue by GruffyPuffy** [rorr73/LifeSOSpy_MQTT#5]
Hi!
First thanks for this work! I just got it running on my WeBeHome version (LS-30). In my system I have the WeBeHome gateway (z-wave) connected but I wanted to get rid of that (paid service) as I am using HA for all my stuff now. I did not have the network module for my LS-30, but the gateway came with a $20 USB-to-Serial module that I simply plugged into a Pi3 instead og the provided gateway. Then, I set up a conversion from serial to tcp using ser2net. After this, I configured LifeSOSpy_MQTT to connect to this IP/port (localhost) and I just wanted to tell you that this works nicely. That means that LifeSOSpy_MQTT will work without the ethernet module as long as you can get your serial data into a Pi (or something else). I guess an alternative could be to set it up using socat also, but I selected ser2net this time. 
Thanks gain! 

Sorry to post this an issue, but I wanted to let you know in some way.
Stefan

**Comment by rorr73** [comment]
Thanks for providing this feedback Stefan; it may be handy for users in a similar situation.
