### ISSUE TITLE
HassIO plugin

### ISSUE THREAD

**Issue by bratanon** [rorr73/LifeSOSpy_MQTT#6]
First of, really good job. This lib works awesome for me. (Using it with LS-20). 

I'm wondering if you have any plans to build a HassIO-addon with this lib?

I would love that myself, and I will try to do that, but want to see if there are any work in progress before I start. 

I saw that someone has made a docker container with what I assume is this lib already. https://hub.docker.com/r/rpavlyuk/c7-lifesospy_mqtt. Is that you? If so, do you have any documentation on that or links where I can find the source code for the container?

**Comment by rorr73** [comment]
Thanks; good to hear it is working on the LS-20 too!

Unfortunately my spare time is very limited these days, so I don't have any plans to build a HassIO addon. If that is something you wish to try, please feel free.

Note the docker container linked above isn't mine... I've never tried creating a Docker container so can't really help you there.

**Comment by bratanon** [comment]
Thanks for the quick reply. I will get back if I manage to do a usefull addon for Hassio.
