### ISSUE TITLE
Feature request: Device battery binary sensor for HA

### ISSUE THREAD

**Issue by bratanon** [rorr73/LifeSOSpy_MQTT#9]
It would be nice to have a binary sensor that shows the device battery status in Home Assistant.

We could make use of the `BatteryLow` and `PowerOnReset` event codes and present a low battery binary sensor that listen to the `[device_id]/event_code` topic. 

The fact the the events are not retained doesnt matter as Home Assistant will keep track of the status for us in case of a connection lost/restart situation.

**Comment by rorr73** [comment]
Thanks for this addition :thumbsup: It has been deployed in 0.11.4

**Comment by papou-github** [comment]
Hi,
First of all, thanks for this add on, it work like a charm !

I just have an issue with the battery sensor: Is having a battery state "unknown" is normal ?

Here is an extract of my config.yaml

- device_id: '824590'
      topic: home/garage/motion
      auto_reset_interval: 180
      ha_name: "Garage Motion"
      ha_name_rssi: "Garage Motion RSSI"
      ha_name_battery: "Garage Motion Battery"

The state for binary_sensor.garage_motion_battery is "unknown" .
And all my LS30 devices have the state issue (smoke sensors & motion sensors)
Thanks for your help.

**Comment by bratanon** [comment]
@papou-github Since HA 2022.2.X its the case.
